plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/tmp/cc-agent/66630284/project/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "yarn run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]